
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "database-agent"
version = "1.4.0"
dependencies = ["anthropic","openai","mysql-connector-python","pyodbc","python-dotenv","pyyaml","psycopg2","sqlglot"]
description = "Agent for database development"
readme = "README.md"
requires-python = ">=3.10"

[project.optional-dependencies]
dev = ["pytest"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
pythonpath = ["src"]
